import 'dart:async';
import 'package:flutter/material.dart';
void main()=>runApp(const QeydApp());
class QeydApp extends StatelessWidget{const QeydApp({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Qeyd App',theme:ThemeData(brightness:Brightness.dark,useMaterial3:true,colorSchemeSeed:const Color(0xffdab873),scaffoldBackgroundColor:const Color(0xff03111e)),home:const SplashPage());}
class SplashPage extends StatefulWidget{const SplashPage({super.key});@override State<SplashPage> createState()=>_SplashPageState();}
class _SplashPageState extends State<SplashPage>{@override void initState(){super.initState();Timer(const Duration(seconds:3),(){if(mounted)Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>const HomePage()));});}@override Widget build(BuildContext c)=>Scaffold(body:Container(decoration:const BoxDecoration(gradient:RadialGradient(center:Alignment(0,-.35),radius:1.2,colors:[Color(0xff173d59),Color(0xff071827),Color(0xff020910)])),child:SafeArea(child:Column(children:[const Spacer(flex:2),Container(width:130,height:130,decoration:BoxDecoration(color:const Color(0xdd071a29),borderRadius:BorderRadius.circular(32),border:Border.all(color:const Color(0xffdab873),width:2),boxShadow:const [BoxShadow(color:Color(0x553ac4ff),blurRadius:34)]),child:const Icon(Icons.auto_stories_rounded,size:66,color:Color(0xffffdfa1))),const SizedBox(height:28),const Text('Qeyd App',style:TextStyle(fontFamily:'serif',fontSize:40,color:Color(0xffffe8bd))),const SizedBox(height:12),const Text('K İ T A B L A R',style:TextStyle(letterSpacing:5,color:Color(0xffdab873))),const SizedBox(height:34),const Padding(padding:EdgeInsets.symmetric(horizontal:42),child:Text('Biliklərini oxu, qeydlərini saxla və istədiyin zaman yenidən nəzərdən keçir.',textAlign:TextAlign.center,style:TextStyle(height:1.7,color:Color(0xffccd5dc)))),const Spacer(),const CircularProgressIndicator(color:Color(0xffdab873)),const SizedBox(height:14),const Text('Yüklənir...'),const Spacer(),const Text('QEYD APP',style:TextStyle(letterSpacing:3,color:Color(0xff9cacb8),fontSize:11)),const SizedBox(height:22)])))));}
class HomePage extends StatefulWidget{const HomePage({super.key});@override State<HomePage> createState()=>_HomePageState();}
class _HomePageState extends State<HomePage>{int i=0;static const pages=[BooksView(),Center(child:Text('Əlfəcinlər hələ boşdur')),Center(child:Text('Axtarış')),Center(child:Text('Ayarlar'))];@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Qeyd App',style:TextStyle(fontFamily:'serif')),actions:[IconButton(onPressed:()=>setState(()=>i=2),icon:const Icon(Icons.search))]),body:pages[i],bottomNavigationBar:NavigationBar(selectedIndex:i,onDestinationSelected:(v)=>setState(()=>i=v),destinations:const [NavigationDestination(icon:Icon(Icons.menu_book),label:'Kitablar'),NavigationDestination(icon:Icon(Icons.bookmark_border),label:'Əlfəcinlər'),NavigationDestination(icon:Icon(Icons.search),label:'Axtarış'),NavigationDestination(icon:Icon(Icons.settings_outlined),label:'Ayarlar')])));}
class BooksView extends StatelessWidget{const BooksView({super.key});@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(18),children:[Container(padding:const EdgeInsets.all(24),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xff173c57),Color(0xff6b4826)]),borderRadius:BorderRadius.circular(22)),child:const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('“Bilik qəlbin işığıdır.”',style:TextStyle(fontFamily:'serif',fontSize:23,color:Color(0xffffe5b1))),SizedBox(height:8),Text('Oxu, qeyd et və yadda saxla.')])),const SizedBox(height:28),const Text('Kitablar',style:TextStyle(fontSize:26,fontWeight:FontWeight.bold)),const SizedBox(height:12),const Card(child:Padding(padding:EdgeInsets.all(22),child:Column(children:[Icon(Icons.library_add_outlined,size:48,color:Color(0xffdab873)),SizedBox(height:12),Text('Kitablar sonradan əlavə olunacaq'),SizedBox(height:6),Text('Tətbiqin əsas quruluşu hazırdır.',style:TextStyle(color:Colors.grey))])))]);}
